# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=26.2.0
group=com.coolerpromc.terracottathings
java_version=25

# Common
minecraft_version=26.2-pre-2
mod_name=TerracottaThings
mod_author=CoolerProMC
mod_id=terracottathings
license=MIT
credits=
description=Add terracotta related functional block to the game
minecraft_version_range=[26.2, 26.3)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.2-pre-2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.150.1+26.2
fabric_loader_version=0.19.0
fabric_mc_version_range=~26.2-pre.2

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.7-beta
neoforge_loader_version_range=[4,)

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
forge_version=64.0.8
forge_loader_version_range=[64,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Dependencies
dependencies_mc_version=26.1.2