package com.coolerpromc.terracottathings.datagen;

import com.coolerpromc.terracottathings.Constants;
import com.coolerpromc.terracottathings.block.TTBlocks;
import net.minecraft.client.data.models.BlockModelGenerators;
import net.minecraft.client.data.models.ItemModelGenerators;
import net.minecraft.client.data.models.ModelProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

public class TTModelProvider extends ModelProvider {
    public TTModelProvider(PackOutput output) {
        super(output, Constants.MODID);
    }

    @Override
    protected void registerModels(BlockModelGenerators blockModels, ItemModelGenerators itemModels) {
        registerAll(blockModels, TTBlocks.TERRACOTTA_BUTTON.get(), TTBlocks.TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.TERRACOTTA_STAIRS.get(), TTBlocks.TERRACOTTA_SLAB.get(), TTBlocks.TERRACOTTA_WALL.get(), Blocks.TERRACOTTA);
        registerAll(blockModels, TTBlocks.WHITE_TERRACOTTA_BUTTON.get(), TTBlocks.WHITE_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.WHITE_TERRACOTTA_STAIRS.get(), TTBlocks.WHITE_TERRACOTTA_SLAB.get(), TTBlocks.WHITE_TERRACOTTA_WALL.get(), Blocks.WHITE_TERRACOTTA);
        registerAll(blockModels, TTBlocks.WHITE_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.WHITE_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.WHITE_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.WHITE_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.WHITE_GLAZED_TERRACOTTA_WALL.get(), Blocks.WHITE_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.ORANGE_TERRACOTTA_BUTTON.get(), TTBlocks.ORANGE_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.ORANGE_TERRACOTTA_STAIRS.get(), TTBlocks.ORANGE_TERRACOTTA_SLAB.get(), TTBlocks.ORANGE_TERRACOTTA_WALL.get(), Blocks.ORANGE_TERRACOTTA);
        registerAll(blockModels, TTBlocks.ORANGE_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.ORANGE_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.ORANGE_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.ORANGE_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.ORANGE_GLAZED_TERRACOTTA_WALL.get(), Blocks.ORANGE_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.MAGENTA_TERRACOTTA_BUTTON.get(), TTBlocks.MAGENTA_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.MAGENTA_TERRACOTTA_STAIRS.get(), TTBlocks.MAGENTA_TERRACOTTA_SLAB.get(), TTBlocks.MAGENTA_TERRACOTTA_WALL.get(), Blocks.MAGENTA_TERRACOTTA);
        registerAll(blockModels, TTBlocks.MAGENTA_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.MAGENTA_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.MAGENTA_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.MAGENTA_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.MAGENTA_GLAZED_TERRACOTTA_WALL.get(), Blocks.MAGENTA_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.LIGHT_BLUE_TERRACOTTA_BUTTON.get(), TTBlocks.LIGHT_BLUE_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.LIGHT_BLUE_TERRACOTTA_STAIRS.get(), TTBlocks.LIGHT_BLUE_TERRACOTTA_SLAB.get(), TTBlocks.LIGHT_BLUE_TERRACOTTA_WALL.get(), Blocks.LIGHT_BLUE_TERRACOTTA);
        registerAll(blockModels, TTBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.LIGHT_BLUE_GLAZED_TERRACOTTA_WALL.get(), Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.YELLOW_TERRACOTTA_BUTTON.get(), TTBlocks.YELLOW_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.YELLOW_TERRACOTTA_STAIRS.get(), TTBlocks.YELLOW_TERRACOTTA_SLAB.get(), TTBlocks.YELLOW_TERRACOTTA_WALL.get(), Blocks.YELLOW_TERRACOTTA);
        registerAll(blockModels, TTBlocks.YELLOW_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.YELLOW_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.YELLOW_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.YELLOW_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.YELLOW_GLAZED_TERRACOTTA_WALL.get(), Blocks.YELLOW_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.LIME_TERRACOTTA_BUTTON.get(), TTBlocks.LIME_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.LIME_TERRACOTTA_STAIRS.get(), TTBlocks.LIME_TERRACOTTA_SLAB.get(), TTBlocks.LIME_TERRACOTTA_WALL.get(), Blocks.LIME_TERRACOTTA);
        registerAll(blockModels, TTBlocks.LIME_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.LIME_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.LIME_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.LIME_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.LIME_GLAZED_TERRACOTTA_WALL.get(), Blocks.LIME_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.PINK_TERRACOTTA_BUTTON.get(), TTBlocks.PINK_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.PINK_TERRACOTTA_STAIRS.get(), TTBlocks.PINK_TERRACOTTA_SLAB.get(), TTBlocks.PINK_TERRACOTTA_WALL.get(), Blocks.PINK_TERRACOTTA);
        registerAll(blockModels, TTBlocks.PINK_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.PINK_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.PINK_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.PINK_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.PINK_GLAZED_TERRACOTTA_WALL.get(), Blocks.PINK_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.GRAY_TERRACOTTA_BUTTON.get(), TTBlocks.GRAY_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.GRAY_TERRACOTTA_STAIRS.get(), TTBlocks.GRAY_TERRACOTTA_SLAB.get(), TTBlocks.GRAY_TERRACOTTA_WALL.get(), Blocks.GRAY_TERRACOTTA);
        registerAll(blockModels, TTBlocks.GRAY_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.GRAY_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.GRAY_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.GRAY_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.GRAY_GLAZED_TERRACOTTA_WALL.get(), Blocks.GRAY_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.LIGHT_GRAY_TERRACOTTA_BUTTON.get(), TTBlocks.LIGHT_GRAY_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.LIGHT_GRAY_TERRACOTTA_STAIRS.get(), TTBlocks.LIGHT_GRAY_TERRACOTTA_SLAB.get(), TTBlocks.LIGHT_GRAY_TERRACOTTA_WALL.get(), Blocks.LIGHT_GRAY_TERRACOTTA);
        registerAll(blockModels, TTBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.LIGHT_GRAY_GLAZED_TERRACOTTA_WALL.get(), Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.CYAN_TERRACOTTA_BUTTON.get(), TTBlocks.CYAN_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.CYAN_TERRACOTTA_STAIRS.get(), TTBlocks.CYAN_TERRACOTTA_SLAB.get(), TTBlocks.CYAN_TERRACOTTA_WALL.get(), Blocks.CYAN_TERRACOTTA);
        registerAll(blockModels, TTBlocks.CYAN_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.CYAN_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.CYAN_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.CYAN_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.CYAN_GLAZED_TERRACOTTA_WALL.get(), Blocks.CYAN_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.PURPLE_TERRACOTTA_BUTTON.get(), TTBlocks.PURPLE_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.PURPLE_TERRACOTTA_STAIRS.get(), TTBlocks.PURPLE_TERRACOTTA_SLAB.get(), TTBlocks.PURPLE_TERRACOTTA_WALL.get(), Blocks.PURPLE_TERRACOTTA);
        registerAll(blockModels, TTBlocks.PURPLE_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.PURPLE_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.PURPLE_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.PURPLE_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.PURPLE_GLAZED_TERRACOTTA_WALL.get(), Blocks.PURPLE_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.BLUE_TERRACOTTA_BUTTON.get(), TTBlocks.BLUE_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.BLUE_TERRACOTTA_STAIRS.get(), TTBlocks.BLUE_TERRACOTTA_SLAB.get(), TTBlocks.BLUE_TERRACOTTA_WALL.get(), Blocks.BLUE_TERRACOTTA);
        registerAll(blockModels, TTBlocks.BLUE_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.BLUE_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.BLUE_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.BLUE_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.BLUE_GLAZED_TERRACOTTA_WALL.get(), Blocks.BLUE_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.BROWN_TERRACOTTA_BUTTON.get(), TTBlocks.BROWN_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.BROWN_TERRACOTTA_STAIRS.get(), TTBlocks.BROWN_TERRACOTTA_SLAB.get(), TTBlocks.BROWN_TERRACOTTA_WALL.get(), Blocks.BROWN_TERRACOTTA);
        registerAll(blockModels, TTBlocks.BROWN_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.BROWN_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.BROWN_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.BROWN_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.BROWN_GLAZED_TERRACOTTA_WALL.get(), Blocks.BROWN_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.GREEN_TERRACOTTA_BUTTON.get(), TTBlocks.GREEN_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.GREEN_TERRACOTTA_STAIRS.get(), TTBlocks.GREEN_TERRACOTTA_SLAB.get(), TTBlocks.GREEN_TERRACOTTA_WALL.get(), Blocks.GREEN_TERRACOTTA);
        registerAll(blockModels, TTBlocks.GREEN_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.GREEN_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.GREEN_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.GREEN_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.GREEN_GLAZED_TERRACOTTA_WALL.get(), Blocks.GREEN_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.RED_TERRACOTTA_BUTTON.get(), TTBlocks.RED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.RED_TERRACOTTA_STAIRS.get(), TTBlocks.RED_TERRACOTTA_SLAB.get(), TTBlocks.RED_TERRACOTTA_WALL.get(), Blocks.RED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.RED_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.RED_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.RED_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.RED_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.RED_GLAZED_TERRACOTTA_WALL.get(), Blocks.RED_GLAZED_TERRACOTTA);
        registerAll(blockModels, TTBlocks.BLACK_TERRACOTTA_BUTTON.get(), TTBlocks.BLACK_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.BLACK_TERRACOTTA_STAIRS.get(), TTBlocks.BLACK_TERRACOTTA_SLAB.get(), TTBlocks.BLACK_TERRACOTTA_WALL.get(), Blocks.BLACK_TERRACOTTA);
        registerAll(blockModels, TTBlocks.BLACK_GLAZED_TERRACOTTA_BUTTON.get(), TTBlocks.BLACK_GLAZED_TERRACOTTA_PRESSURE_PLATE.get(), TTBlocks.BLACK_GLAZED_TERRACOTTA_STAIRS.get(), TTBlocks.BLACK_GLAZED_TERRACOTTA_SLAB.get(), TTBlocks.BLACK_GLAZED_TERRACOTTA_WALL.get(), Blocks.BLACK_GLAZED_TERRACOTTA);
    }

    private void registerAll(BlockModelGenerators gen, Block button, Block pressurePlate, Block stairs, Block slab, Block wall, Block textureSource) {
        gen.familyWithExistingFullBlock(textureSource).button(button).pressurePlate(pressurePlate).stairs(stairs).slab(slab).wall(wall);
    }
}
