plugins {
    id 'multiloader-loader'
    id 'net.minecraftforge.gradle'
    id 'idea'
    id "me.modmuss50.mod-publish-plugin"
}
base {
    archivesName = "${mod_name}-forge-${minecraft_version}"
}

jar {
    manifest {
        attributes["MixinConfigs"] = "${mod_id}.mixins.json,${mod_id}.forge.mixins.json"
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    // Automatically enable forge AccessTransformers if the file exists
    // This location is hardcoded in Forge and can not be changed.
    // https://github.com/MinecraftForge/MinecraftForge/blob/be1698bb1554f9c8fa2f58e32b9ab70bc4385e60/fmlloader/src/main/java/net/minecraftforge/fml/loading/moddiscovery/ModFile.java#L123
    // Forge still uses SRG names during compile time, so we cannot use the common AT's
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformer = at
    }

    runs {
        client {
            workingDir.convention layout.projectDirectory.dir('runs/client')
        }

        server {
            workingDir.convention layout.projectDirectory.dir('runs/server')
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

sourceSets.main.resources.srcDir 'src/generated/resources'

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:$minecraft_version-$forge_version")
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'
}

sourceSets.each {
    def dir = layout.buildDirectory.dir("sourcesSets/$it.name")
    it.output.resourcesDir = dir
    it.java.destinationDirectory = dir
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'forge')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'forge')
            }
        }
    }
}

publishMods {
    file.set(jar.archiveFile)
    type = STABLE
    modLoaders.add("forge")
    changelog = rootProject.file("changelog.md").text
    displayName = mod_id + "-" + project.version + "+" + minecraft_version + "-forge"

    curseforge {
        projectId = "1548711"
        accessToken = findProperty("CF_TOKEN")
        changelogType = "markdown"
        minecraftVersions.add(minecraft_version)
    }

    modrinth {
        projectId = 'gEsy4oZy'
        accessToken = findProperty("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
    }
}